### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by PoeticExposition** [lihaokun/RootOfMTP#1]
The [README.md](https://github.com/lihaokun/RootOfMTP/blob/main/README.md) says that algorithm details can be viewed in https://arxiv.org/abs/2202.06044, but isn't the address https://arxiv.org/pdf/2301.05847.pdf#page=35?

**Comment by lihaokun** [comment]
Hi, you are correct. The correct link to view the algorithm details should be https://arxiv.org/pdf/2301.05847.pdf#page=35. We have updated the README.md to reflect this change. Thank you for pointing this out!
